# Dockerfile.mysql
FROM mysql:oracle

# Set the root password, change as needed
ENV MYSQL_ROOT_PASSWORD=rootpassword

# Create a database, change as needed
ENV MYSQL_DATABASE=mydatabase

# Create a user and set a password, change as needed
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# Copy the schema.sql file to the docker-entrypoint-initdb.d directory
COPY /sql/schema.sql /docker-entrypoint-initdb.d/

# Expose port 3306
EXPOSE 3306
